### ISSUE TITLE
alter welcome message

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/orfeo#1]
@rodica-andronache child themes should be able to alter the welcome message, I think is pretty important to mention like : welcome to orfeo, a cool hestia child theme. Get started with Orfeo .

**Comment by ineagu** [comment]
https://www.dropbox.com/s/b7tqipeddx71qlo/Screenshot%202018-01-09%2015.59.55.png?dl=0

**Comment by ineagu** [comment]
@rodica-andronache can we do that?

**Comment by rodica-andronache** [comment]
yes, we'll do this too
