### ISSUE TITLE
Second Header Button default values

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/orfeo#14]
The second button within Big Title Section, the one with white border doesn't have default values in the customizer.

**Comment by rodica-andronache** [comment]
@stefan-cotitosu 
i don't think the accent color is well filtered. this part doesn't make sense for me https://github.com/Codeinwp/orfeo/blob/master/functions.php#L191 . I don't understand what the color should be. it's blue on the header, red in the customizer. We can talk about this tomorrow
