### ISSUE TITLE
Woocommerce Coupon message shows in the incorrect size

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/orfeo#18]
@rodica-andronache When we apply a coupon code on the checkout page, then woocommerce message appears in the incorrect size. See http://prntscr.com/il0m1d

**Comment by stefan-cotitosu** [comment]
Thank you @poonam279 for reporting this. I've just discovered the 'Apply coupon' button which wasn't styled as the other buttons within the theme. 👍
