### ISSUE TITLE
Header Second Button Missing Controls

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/orfeo#21]
Since we add the tabs customizer control in Hestia, the controls for the second button text and link are hidden. The second button is in Big Title section.

**Comment by rodica-andronache** [comment]
@stefan-cotitosu until we decide if we'll release an update or do something else, let's create a short doc with a solution in orfeo, to add the controls somewhere in customizer. Doesn't have to be in the Big title section (if it's not possible) just have it there somewhere, so users could use that button. It seems really frustrating at this point.

After that, we can answer here https://wordpress.org/support/topic/second-big-title-button-no-control/#topic-10199759-replies

**Comment by cristian-ungureanu** [comment]
solved here https://github.com/Codeinwp/hestia-pro/pull/1613

**Comment by rodica-andronache** [comment]
added a comment there
