### ISSUE TITLE
Header second button alignment

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/orfeo#22]
The two buttons on the front page is not aligned on mobile view.

Image: https://themeisle.com/index.php?gf-download=2018%2F05%2FScreenshot_20180520-004455.png&form-id=1&field-id=19&hash=8feb9372f308d5a9e8a2822fe2681bb20fa68ba98fd0619cdf300419717c91b5

The problem arises when the device width is between 411 to 755px (around values).

When the width is lower than 411px(around) the buttons stick together: http://prntscr.com/jkiqcx

Following code worked for me in both the cases; however, we have used different margin in the same class currently. 

`@media (max-width: 768px){
.carousel .buttons .btn-left + .btn-right, .carousel .buttons .btn-left, .carousel .buttons .btn-right {
    margin: 15px;
}
}`

Ticket: https://secure.helpscout.net/conversation/584158121/162001/

@rodica-andronache

**Comment by rodica-andronache** [comment]
@stefan-cotitosu you can try to tackle this in the code 👍 ( when we'll have more issues fixed, we may release an update ) and also maybe have a doc with the fix so we can give to users ( don't recommend working directly on the child theme, but to add some css in the advanced css tab )
