### ISSUE TITLE
Header first button border radius missing

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/orfeo#24]
@rodica-andronache With the Hestia Version 2.0.4, the first button of big title section appears in square shape. It should be in round shape like other buttons.
See screenshot: http://prntscr.com/ku99tz http://prntscr.com/ku9ade

**Comment by rodica-andronache** [comment]
@stefan-cotitosu first check if there something we can do from the parent theme :)

**Comment by stefan-cotitosu** [comment]
@poonam279 I've fixed this, you can see the commits on branch **orfeo-fixes** on my fork
Let me know if you have any thoughts about this one.

The buttons styling feature will not work anymore on that button. (Left button in Big Title Section on Orfeo child theme)
