### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/orfeo#3]
- [x] change default font family in customizer too, to match the one in front-end https://prnt.sc/hzgcy9
- [x] Shopping cart widget in sidebar https://prnt.sc/hzhfns . The problem with the Search widget is from Hestia, and will be fixed there
- [x] Page title is vertically centered on the blog, but there are other pages where is not, for example, the search results page https://prnt.sc/hzhjh2 , the archive https://prnt.sc/hzhjxm, 404 page. I'm not sure if this is how it's supposed to be
- [x] I think it would be a good idea to escape all occurrences of $color_accent in orfeo_inline_style with esc_attr or esc_html

**Comment by rodica-andronache** [comment]
- [ ] view cart button position 
![screenshot 1](https://user-images.githubusercontent.com/3266155/35038150-893eb3cc-fb82-11e7-8ef6-e1946f16ee76.png)
- [ ] not able to change the font family for headings

**Comment by rodica-andronache** [comment]
- [ ] on single post page it's a weird space, is that ok? https://prnt.sc/i1nev1

**Comment by rodica-andronache** [comment]
@stefan-cotitosu the screenshot should be 1200×900, not 373x280 :D  https://wp.zacgordon.com/2013/03/04/the-correct-size-for-a-wordpress-theme-screenshot-is-600x450/

**Comment by rodica-andronache** [comment]
- [ ] sticky posts on blog - differentiate them somehow + the image is to high https://demo.themeisle.com/orfeo/blog/

**Comment by rodica-andronache** [comment]
- [ ] view cart button missing from notice https://prnt.sc/i1rc3i

**Comment by rodica-andronache** [comment]
- [ ] maybe apply some padding to this buttons on the cart page https://prnt.sc/i1rdi5 ? Not sure if it was intended like this

**Comment by rodica-andronache** [comment]
- [ ] on shop too, the problem with the main-raised class, http://forks.themeisle.com/codeinwp/orfeo/development/shop/ maybe check all pages for this

**Comment by ineagu** [comment]
page title "Cart" need some padding as well :)
